### ISSUE TITLE
帖子详情页中的BACK按钮偶尔会一直显示，还有Back按钮的图标可以换一个

### ISSUE THREAD

**Issue by xingfuqiu** [ruby-china/ruby-china-ios#11]

**Comment by klaus01** [comment]
> back按钮偶尔会一直显示

没明白你的意思。现在每个界面的back按钮是一直显示在左上角的，你是说这个按钮偶尔会消失？

> Back按钮的图标可以换一个

换的目的是什么呢？现在用系统的挺好的。

**Comment by huacnlee** [comment]
back 图标可以显示“返回”两个字，NavigationBar 有足够的宽度

**Comment by klaus01** [comment]
之前调整了界面组织结构，现在应该不会偶尔显示“返回”字样了。
