### ISSUE TITLE
应该有一个自制能自动刷新或尝试拉取话题列表的新数据

### ISSUE THREAD

**Issue by huacnlee** [ruby-china/ruby-china-ios#13]
我昨晚打开的列表，几天早上打开 App，哪个位置还是昨晚的内容。

**Comment by klaus01** [comment]
需要这个机制吗？印象中没有应用这么搞的。

晚上回去试试，睡前打开几个应用的列表界面，早上起来再打开看会不会自动刷新。（进程被结束，重新启动的不算）

**Comment by klaus01** [comment]
试了 MONO、ifanr 和数字尾巴，没有做这种逻辑。这类应用在没有结束进程的情况都是用户主动刷新，只有微信微博这类应用会主动显示有多少新内容。

其实要做这个功能是很简单的，只是需要定个“间隔时长”，应用被切入后台多少小时后再进入应用需要刷新。先定个 2 小时看看。

**Comment by huacnlee** [comment]
这个放后面再说吧
