### ISSUE TITLE
登录后到 accessToken 过期这段时间，如果应用进程一直没结束，则 accessToken 没有刷新

### ISSUE THREAD

**Issue by klaus01** [ruby-china/ruby-china-ios#18]
目前 refresh access token 操作只在应用启动时做了，还需要修复上面说的情况。

**Comment by huacnlee** [comment]
~~请求通知数量的时候会有 HTTP Status，401 的时候就需要刷新了，或许可以利用这个~~

**Comment by huacnlee** [comment]
其实 accessToken 的有效期是在 OAuth 结果返回出来的，可以基于哪个来存储 accessToken 并自动过期，然后 refreshToken 也是有有效期的时间返回的。
