### ISSUE TITLE
有开发的标准或者 guideline 之类的吗？

### ISSUE THREAD

**Issue by tesths** [ruby-china/ruby-china-ios#25]
想参与到开发当中，想问问有没有一些标准，代码和内容。

**Comment by huacnlee** [comment]
标准？

**Comment by huacnlee** [comment]
iOS Native 方面 @klaus01 负责，你可以先实现，然后提 PR 等 Review 好了

**Comment by klaus01** [comment]
就代码风格而言，目前是个人经验风格。可以讨论一下使用哪种风格。如：
https://github.com/github/swift-style-guide
https://github.com/raywenderlich/swift-style-guide

**Comment by jasl** [comment]
ray的！我是contributor 哈哈

--
Hotmail
Sent with Airmail


开 21 September 2016 在 18:11:10, 柯磊 (notifications@github.com<mailto:notifications@github.com>) 写到:

就代码风格而言，目前是个人经验风格。可以讨论一下使用哪种风格。如：
https://github.com/github/swift-style-guide
https://github.com/raywenderlich/swift-style-guide

**Comment by jasl** [comment]
支持Ray的，我是贡献者哈哈

**Comment by tesths** [comment]
功能上有没有什么标准或者没有完成的部分？

**Comment by klaus01** [comment]
需求主要是 @huacnlee 在确定，有什么想法可以先讨论再做。
