### ISSUE TITLE
内容带 Youtube 视频的，打开后会跳到空白页面

### ISSUE THREAD

**Issue by huacnlee** [ruby-china/ruby-china-ios#28]
最近增加了 Youtube 视频嵌入的功能，iOS 客户端打开那种页面会跑到一个空白页面去。

https://ruby-china.org/topics/31241

**Comment by huacnlee** [comment]
swift-2.3 是不是可以合并 master 了？

**Comment by klaus01** [comment]
可以，已经合了。
