### ISSUE TITLE
增加快速到话题底部的功能

### ISSUE THREAD

**Issue by huacnlee** [ruby-china/ruby-china-ios#29]
有些文章非常长，同时回复也很多，要阅读后面的需要拖动很久才可以，需要增加一个按钮，快速到顶部和底部。

不知道 iOS UI 里面有没有类似的场景例子可以参考。

**Comment by klaus01** [comment]
快速到顶部是点击屏幕顶部的 StatusBar。快速到底部在 iOS 上没见过类似的操作。
