### ISSUE TITLE
奇怪，我编译不过

### ISSUE THREAD

**Issue by huacnlee** [ruby-china/ruby-china-ios#32]
```
/Users/jason/work/ruby-china-ios/Pods/DGElasticPullToRefresh/DGElasticPullToRefresh/DGElasticPullToRefreshExtensions.swift:165:94: 
Downcast from 'CALayer?' to 'CALayer' only unwraps optionals; did you mean to use '!'?
```

**Comment by huacnlee** [comment]
<img width="921" alt="2016-10-16 10 55 44" src="https://cloud.githubusercontent.com/assets/5518/19414907/1cfbd9b2-938f-11e6-8a6c-49ac4a3babbf.png">

**Comment by klaus01** [comment]
因 Swift 版本问题，DGElasticPullToRefresh 需要改下代码才行，报错那行删除后面的 as? CALayer 及可。

使用 DGElasticPullToRefresh 的过程中发现有问题，我在考虑换别的 Refresh 库。
