### ISSUE TITLE
从话题返回列表的时候，需要触发一下 PullToRefresh 以便载入新数据

### ISSUE THREAD

**Issue by huacnlee** [ruby-china/ruby-china-ios#33]
- [ ] ~~从话题返回列表的时候，需要触发一下 PullToRefresh 以便载入新数据~~
- [x] 分页一次加载的数量需要增加到 40;
- [x] （赞、关注、收藏）CSS 上隐藏页面的； 
- [x] 已关注、已赞的样式不够明显，需要显示赞的数量；
- [x] `PKHUD` 的样式不够好，如果可以的话该用 [MBProgressHUD](https://github.com/jdg/MBProgressHUD)
- [x] 搜索界面带过去的 access_token 参数拼接不对，出现两个 `?` 了

**Comment by klaus01** [comment]
> 从话题返回列表的时候，需要触发一下 PullToRefresh 以便载入新数据

刷新的目的是什么？
这样刷新会打断用户的浏览，如：我在帖子列表中往上慢慢滚，看到一个感兴趣的帖子，点进去查看，再返回到列表后自动做了刷新操作，这时帖子的位置和顺序可能发生了变化，我就不知道之前我浏览到哪个位置了！

> （赞、关注、收藏）CSS 上隐藏页面的；

这个是客户端调用 JavaScript 实现？还是网页那边处理？

> PKHUD 的样式不够好，如果可以的话该用 MBProgressHUD

可以。其实我在 Objective-C 中一直用 MBProgressHUD，当初用 PKHUD 是想用个 Swift 版本的 HUD。

**Comment by huacnlee** [comment]
第一条算了吧，可以下拉刷新。

第二个 Web 端实现

**Comment by huacnlee** [comment]
关于列表返回更新的实现，Turbolinks 的方式是默默请求，然后替换掉，滚动条位置保持不变的。

不知道 Native 是否能实现

**Comment by klaus01** [comment]
> 关于列表返回更新的实现，Turbolinks 的方式是默默请求，然后替换掉，滚动条位置保持不变的。
> 不知道 Native 是否能实现

可以做到后台刷新滚动条位置不变，但刷新数据后帖子的位置可能发生变化。

**Comment by huacnlee** [comment]
那保持不变吧

**Comment by klaus01** [comment]
- [ ] ~~去掉帖子的“移到尾部”功能，在 WebView 中增加一个滑块来实现快速滚动功能~~

**Comment by huacnlee** [comment]
HTML 隐藏那个几个功能，需要等着版本发布以后再隐藏，不然目前 App Store 的版本就没法用哪几个功能了。

**Comment by klaus01** [comment]
那你只针对 iOS 客户端进行隐藏？Android 那边不能隐藏吧！

**Comment by huacnlee** [comment]
<img width="324" alt="2016-10-26 1 48 55" src="https://cloud.githubusercontent.com/assets/5518/19714717/f9214224-9b82-11e6-9d25-af34704685ff.png">

这样似乎不太好，不如在话题底部增加一栏按钮，同时包含回复按钮（定位到回复文本框）？

**Comment by huacnlee** [comment]
User-Agent 增加版本 `iOS, version:2.1` 以后以版本来处理特别的覆盖

**Comment by klaus01** [comment]
你是说滑块吗？滑块在视觉上类似 iOS 的 AssistiveTouch，然后不会那么大。

**Comment by klaus01** [comment]
直接放个“定位回复框”的按钮我也想过，后来还是觉得滑块更好用些，滑块还能解决阅读长文的一些需求。

**Comment by huacnlee** [comment]
给个例子🌰看看

**Comment by huacnlee** [comment]
``` rb
def turbolinks_ios?
    turbolinks_app? && request.user_agent.to_s.include?('iOS')
  end

  def turbolinks_app_version
    return '' if !turbolinks_app?
    return @turbolinks_app_version if defined? @turbolinks_app_version
    version_str = request.user_agent.to_s.match(/version:[\d\.]+/).to_s
    @turbolinks_app_version = version_str.split(':').last
    return @turbolinks_app_version
  end
```

新增两个函数判断环境

**Comment by huacnlee** [comment]
``` swift
let USER_AGENT = "turbolinks-app, ruby-china, official, iOS, version:2.1"
```

**Comment by klaus01** [comment]
例子一时找不到，AssistiveTouch 网上能搜到图片，这种设计我是见过的。
