### ISSUE TITLE
需要处理网络超时

### ISSUE THREAD

**Issue by huacnlee** [ruby-china/ruby-china-ios#35]
现在如果网络状态不佳的情况，PullToRefresh 需要等很久才会失败，应该设定一个限时，例如 (3s)，超时以后保持之前的数据不变（目前可能会是白屏）

此外，Turbolinks 由于列表没有用 WebView 了，话题查看页面首次打开的时候慢多了（因为 WebKit 还没初始化），还得想个法优化一下

**Comment by klaus01** [comment]
超时时间可以改短一些。当没有数据时如果出现网络错误就在界面上显示长住错误提示，点击或下拉重新加载。当有数据时出现网络错误就用 HUD 提示，保持着之前的数据。

初始化 Turbolinks 慢的问题，考虑启动时后台加载一个看不见的 WKWebView。
