### ISSUE TITLE
首页里面的navigationbar的扩展里面bottomBorder是干什么的？

### ISSUE THREAD

**Issue by asasdasasd** [ruby-china/ruby-china-ios#45]
height为1的bottomBorder。。。

**Comment by klaus01** [comment]
就 NavigationBar 下边的边线呀，如图：
![wx20161215-222214](https://cloud.githubusercontent.com/assets/338228/21227452/0a0dbfb8-c315-11e6-8dd8-ef2cbbfa61f1.png)

**Comment by asasdasasd** [comment]
加这条线只是因为设计的原因么。。。。。

**Comment by klaus01** [comment]
@huacnlee 加的。应该是视觉上的考虑。
