### ISSUE TITLE
（在糟糕网络环境？）登录后进入收藏tab后无限闪退

### ISSUE THREAD

**Issue by jasl** [ruby-china/ruby-china-ios#47]
问题版本：Testflight的当前测试版本

经过我在本地debug的结果来看，原因是`OAuth2.shard.currentUser`在登录后仍可能是`nil`
导致 <https://github.com/ruby-china/ruby-china-ios/blob/master/ruby-china-ios/Controllers/FavoriteTopicsViewController.swift#L23> `let userLogin = OAuth2.shared.currentUser!.login` 强制解包失败，造成闪退，似乎App会记录最后一次页面，于是造成无限闪退。

推测：[登录方法](https://github.com/ruby-china/ruby-china-ios/blob/master/ruby-china-ios/Libraries/OAuth2.swift#L65) 会触发 `self.reloadCurrentUser()` 该方法调用的 [UserService.me](https://github.com/ruby-china/ruby-china-ios/blob/master/ruby-china-ios/Libraries/UsersService.swift#L15) 为异步方法，如果网络环境较差没有及时响应则会导致`accessToken` 正确设置，`isLogin()` 返回 `true`，但是 `currentUser` 仍为 `nil`，通过短路强制解包`currentUser`的相关代码后，侧边栏为未登录状态，而通知等tab内容显示正常，可以验证推测。

**Comment by klaus01** [comment]
@jasl 
我没有重现无限闪退的情况，App 并没有记录最后一次页面。

我的测试是，未登录状态启动应用，点击"收藏"会弹出登录界面，这时登录后就会 crash，正是你所定位到的代码问题。同时你推测的问题也确实存在。都进行了相应修复。

感谢反馈。

**Comment by jasl** [comment]
我现在在国外，发现 Ruby-China 的API会经常返回503响应（日志里有体现），不知道是不是服务器的设置使然

另：建议使用Logger库 比如 XCGLogger，不要在代码里直接用 `print`

**Comment by huacnlee** [comment]
503 是节前我配置了 Nginx limit_req，但配错了，/cable 的请求也算进去了，于是就很容易超过 Limit 而 503

**Comment by jasl** [comment]
OK

**Comment by jasl** [comment]
@huacnlee 发个testflight测试哈

**Comment by huacnlee** [comment]
@jasl 不需要啊，是服务器修改

下个迭代的 iOS 版本等 App Store release 吧，小修改，没必要发 Testflight

**Comment by jasl** [comment]
我是说我提的那个闪退的情况... 我现在用自己编译的版本
