### ISSUE TITLE
WebKit 请求的 access_token 要通过 Headers 传，减少泄漏

### ISSUE THREAD

**Issue by huacnlee** [ruby-china/ruby-china-ios#49]

**Comment by klaus01** [comment]
暂时没能找到方法在 WKWebView 请求过程中修改 Header (有个链接
 http://stackoverflow.com/questions/28984212/how-to-add-httpheader-in-request-globally-for-ios-swift/37474812 )。

现在想到的办法是修改 turbolinks-ios 的原代码，在 webView.load 之前将 request 传出去让外部可修改 request 内容。但我不想修改 turbolinks-ios 代码，所以有些犹豫。

**Comment by huacnlee** [comment]
这个挺重要的，需要关注一下解决方法

HTTPS 的请求，URL 参数会加密，中间人攻击拦截不到 token，不过 URL 里面带 token 在日志里面也是风险，需要特别过滤，风险较多，所以最好是通过 Header 来传递。

**Comment by klaus01** [comment]
试了修改原码在 webView.load 前外部修改 request 方式，发现 turbolinks-ios 并不是所有的页面跳转都用 webView.load ，有的是在 webView 中执行 JavaScript 的方式实现的页面跳转。以至于修改 request 的方案失败！

再想想。

**Comment by julysiji** [comment]
[!] Error installing FirebaseInstanceID
[!] /usr/bin/curl -f -L -o /var/folders/d8/9702jm995ss_jzjqvpkgj9cm0000gn/T/d20170216-2444-ub97v5/file.tgz https://www.gstatic.com/cpdc/18da95d517c54d0f/FirebaseInstanceID-1.0.8.tar.gz --create-dirs --netrc-optional

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:02:29 --:--:--     0curl: (7) Failed to connect to www.gstatic.com port 443: Operation timed out


这依赖是要翻墙才行？

**Comment by klaus01** [comment]
@julysiji 是的

**Comment by huacnlee** [comment]
@klaus01 那就把哪个改动撤销吧
